apiVersion: apps/v1
kind: Deployment
metadata:
    name: asr-deployment
    labels:
        app: asr-system
spec:
    replicas: 2
    selector:
        matchLabels:
            app: asr-system
    template: 
        metadata:
            labels:
                app: asr-system
        spec:
            containers:
                - name: asr-system 
                  image: krishnadn/deploy_speech:latest
                  ports:
                  - containerPort: 8000