apiVersion: v1
kind: Service
metadata:
    name: asr-service
spec:
    type: LoadBalancer
    selector:
        app: asr-system
    ports:
        - name: asr-port
          port: 80
          targetPort: 8000